name: AI Passport PR Bot

on:
  workflow_dispatch:
    inputs:
      upstream:
        description: "Upstream repo to open PR against (format: owner/repo)"
        required: true
      base_branch:
        description: "Base branch on upstream"
        required: false
        default: "main"
      title:
        description: "PR title"
        required: false
        default: "Add AI Passport (.passport) dataset summary"
      body:
        description: "Extra text for PR body (optional)"
        required: false
        default: ""

permissions:
  contents: write   # write to your fork

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run scanner to generate .passport
        run: |
          python scan.py
          ls -la .passport || true

      - name: Create branch and commit .passport
        id: commit
        run: |
          set -e
          BRANCH="ai-passport/${{ github.run_id }}"
          echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT
          git config user.email "action@github.com"
          git config user.name "ai-passport-bot"
          git checkout -b "$BRANCH"
          git add .passport || true
          if git diff --staged --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            echo "No changes to commit."
          else
            git commit -m "chore: add/update AI Passport (.passport)"
            git push --set-upstream origin "$BRANCH"
          fi

      - name: Stop if there is nothing to PR
        if: steps.commit.outputs.no_changes == 'true'
        run: echo "Nothing to PR." && exit 0

      - name: Create PR to upstream using gh CLI
        env:
          GH_TOKEN: ${{ secrets.PR_BOT_TOKEN }}
        run: |
          set -e
          BRANCH="${{ steps.commit.outputs.BRANCH }}"
          UPSTREAM="${{ github.event.inputs.upstream }}"
          BASE="${{ github.event.inputs.base_branch || 'main' }}"
          TITLE="${{ github.event.inputs.title || 'Add AI Passport (.passport) dataset summary' }}"
          EXTRA="${{ github.event.inputs.body }}"
          HEAD="${{ github.actor }}:${BRANCH}"

          BODY="This PR adds the generated **.passport/** dataset summary (EU-AI-Act-ready).
- Generated by AI Passport Scanner in fork **${{ github.repository }}**
- Run ID: ${{ github.run_id }}

${EXTRA}"

          echo "Creating PR from $HEAD -> $UPSTREAM:$BASE"
          gh pr create --repo "$UPSTREAM" --base "$BASE" --head "$HEAD" --title "$TITLE" --body "$BODY"
